
export default [
  {
    title: "Bleach",
    imageURL: "http://s3.mangapanda.com/cover/bleach/bleach-l0.jpg",
    year: 2017,
    units: 10,
  },
  {
    title: "Naruto",
    imageURL: "http://s3.mangapanda.com/cover/naruto/naruto-l0.jpg",
    year: 2017,
    units: 10,
  },
  {
    title: "One Piece",
    imageURL: "http://s3.mangapanda.com/cover/one-piece/one-piece-l1.jpg",
    year: 2017,
    units: 10,
  },
  {
    title: "Shingeki no Kyojin",
    imageURL: "http://s1.mangapanda.com/cover/shingeki-no-kyojin/shingeki-no-kyojin-l0.jpg",
    year: 2017,
    units: 10,
  },
  {
    title: "Ao No Exorcist",
    imageURL: "http://s5.mangapanda.com/cover/ao-no-exorcist/ao-no-exorcist-l0.jpg",
    year: 2017,
    units: 10,
  },
  {
    title: "Bleach",
    imageURL: "http://s3.mangapanda.com/cover/bleach/bleach-l0.jpg",
    year: 2017,
    units: 10,
  },
  {
    title: "Naruto",
    imageURL: "http://s3.mangapanda.com/cover/naruto/naruto-l0.jpg",
    year: 2017,
    units: 10,
  },
  {
    title: "One Piece",
    imageURL: "http://s3.mangapanda.com/cover/one-piece/one-piece-l1.jpg",
    year: 2017,
    units: 10,
  },
  {
    title: "Shingeki no Kyojin",
    imageURL: "http://s1.mangapanda.com/cover/shingeki-no-kyojin/shingeki-no-kyojin-l0.jpg",
    year: 2017,
    units: 10,
  },
  {
    title: "Ao No Exorcist",
    imageURL: "http://s5.mangapanda.com/cover/ao-no-exorcist/ao-no-exorcist-l0.jpg",
    year: 2017,
    units: 10,
  },
  {
    title: "Bleach",
    imageURL: "http://s3.mangapanda.com/cover/bleach/bleach-l0.jpg",
    year: 2017,
    units: 10,
  },
  {
    title: "Naruto",
    imageURL: "http://s3.mangapanda.com/cover/naruto/naruto-l0.jpg",
    year: 2017,
    units: 10,
  },
  {
    title: "One Piece",
    imageURL: "http://s3.mangapanda.com/cover/one-piece/one-piece-l1.jpg",
    year: 2017,
    units: 10,
  },
  {
    title: "Shingeki no Kyojin",
    imageURL: "http://s1.mangapanda.com/cover/shingeki-no-kyojin/shingeki-no-kyojin-l0.jpg",
    year: 2017,
    units: 10,
  },
  {
    title: "Ao No Exorcist",
    imageURL: "http://s5.mangapanda.com/cover/ao-no-exorcist/ao-no-exorcist-l0.jpg",
    year: 2017,
    units: 10,
  },
  {
    title: "Bleach",
    imageURL: "http://s3.mangapanda.com/cover/bleach/bleach-l0.jpg",
    year: 2017,
    units: 10,
  },
  {
    title: "Naruto",
    imageURL: "http://s3.mangapanda.com/cover/naruto/naruto-l0.jpg",
    year: 2017,
    units: 10,
  },
  {
    title: "One Piece",
    imageURL: "http://s3.mangapanda.com/cover/one-piece/one-piece-l1.jpg",
    year: 2017,
    units: 10,
  },
  {
    title: "Shingeki no Kyojin",
    imageURL: "http://s1.mangapanda.com/cover/shingeki-no-kyojin/shingeki-no-kyojin-l0.jpg",
    year: 2017,
    units: 10,
  },
  {
    title: "Ao No Exorcist",
    imageURL: "http://s5.mangapanda.com/cover/ao-no-exorcist/ao-no-exorcist-l0.jpg",
    year: 2017,
    units: 10,
  },
  {
    title: "Bleach",
    imageURL: "http://s3.mangapanda.com/cover/bleach/bleach-l0.jpg",
    year: 2017,
    units: 10,
  },
  {
    title: "Naruto",
    imageURL: "http://s3.mangapanda.com/cover/naruto/naruto-l0.jpg",
    year: 2017,
    units: 10,
  },
  {
    title: "One Piece",
    imageURL: "http://s3.mangapanda.com/cover/one-piece/one-piece-l1.jpg",
    year: 2017,
    units: 10,
  },
  {
    title: "Shingeki no Kyojin",
    imageURL: "http://s1.mangapanda.com/cover/shingeki-no-kyojin/shingeki-no-kyojin-l0.jpg",
    year: 2017,
    units: 10,
  },
  {
    title: "Ao No Exorcist",
    imageURL: "http://s5.mangapanda.com/cover/ao-no-exorcist/ao-no-exorcist-l0.jpg",
    year: 2017,
    units: 10,
  },
];
