
export default [
  {
    title: "Steins Gate 0",
    imageURL: "https://myanimelist.cdn-dena.com/images/anime/4/77633.jpg",
    year: 2017,
    units: 10,
  },
  {
    title: "One Punch Man",
    imageURL: "https://myanimelist.cdn-dena.com/images/anime/12/76049.jpg",
    year: 2017,
    units: 10,
  },
  {
    title: "Tokyo Ghoul",
    imageURL: "https://myanimelist.cdn-dena.com/images/anime/5/64449.jpg",
    year: 2017,
    units: 10,
  },
  {
    title: "Steins Gate",
    imageURL: "https://myanimelist.cdn-dena.com/images/anime/5/73199.jpg",
    year: 2017,
    units: 10,
  },
  {
    title: "Sword Art Online",
    imageURL: "https://myanimelist.cdn-dena.com/images/anime/11/39717.jpg",
    year: 2017,
    units: 10,
  },
  {
    title: "Log Horizon",
    imageURL: "https://myanimelist.cdn-dena.com/images/anime/5/84004.jpg",
    year: 2017,
    units: 10,
  },
  {
    title: "Steins Gate 0",
    imageURL: "https://myanimelist.cdn-dena.com/images/anime/4/77633.jpg",
    year: 2017,
    units: 10,
  },
  {
    title: "One Punch Man",
    imageURL: "https://myanimelist.cdn-dena.com/images/anime/12/76049.jpg",
    year: 2017,
    units: 10,
  },
  {
    title: "Tokyo Ghoul",
    imageURL: "https://myanimelist.cdn-dena.com/images/anime/5/64449.jpg",
    year: 2017,
    units: 10,
  },
  {
    title: "Steins Gate",
    imageURL: "https://myanimelist.cdn-dena.com/images/anime/5/73199.jpg",
    year: 2017,
    units: 10,
  },
  {
    title: "Sword Art Online",
    imageURL: "https://myanimelist.cdn-dena.com/images/anime/11/39717.jpg",
    year: 2017,
    units: 10,
  },
  {
    title: "Log Horizon",
    imageURL: "https://myanimelist.cdn-dena.com/images/anime/5/84004.jpg",
    year: 2017,
    units: 10,
  },
  {
    title: "Steins Gate 0",
    imageURL: "https://myanimelist.cdn-dena.com/images/anime/4/77633.jpg",
    year: 2017,
    units: 10,
  },
  {
    title: "One Punch Man",
    imageURL: "https://myanimelist.cdn-dena.com/images/anime/12/76049.jpg",
    year: 2017,
    units: 10,
  },
  {
    title: "Tokyo Ghoul",
    imageURL: "https://myanimelist.cdn-dena.com/images/anime/5/64449.jpg",
    year: 2017,
    units: 10,
  },
  {
    title: "Steins Gate",
    imageURL: "https://myanimelist.cdn-dena.com/images/anime/5/73199.jpg",
    year: 2017,
    units: 10,
  },
  {
    title: "Sword Art Online",
    imageURL: "https://myanimelist.cdn-dena.com/images/anime/11/39717.jpg",
    year: 2017,
    units: 10,
  },
  {
    title: "Log Horizon",
    imageURL: "https://myanimelist.cdn-dena.com/images/anime/5/84004.jpg",
    year: 2017,
    units: 10,
  },
  {
    title: "Steins Gate 0",
    imageURL: "https://myanimelist.cdn-dena.com/images/anime/4/77633.jpg",
    year: 2017,
    units: 10,
  },
  {
    title: "One Punch Man",
    imageURL: "https://myanimelist.cdn-dena.com/images/anime/12/76049.jpg",
    year: 2017,
    units: 10,
  },
  {
    title: "Tokyo Ghoul",
    imageURL: "https://myanimelist.cdn-dena.com/images/anime/5/64449.jpg",
    year: 2017,
    units: 10,
  },
  {
    title: "Steins Gate",
    imageURL: "https://myanimelist.cdn-dena.com/images/anime/5/73199.jpg",
    year: 2017,
    units: 10,
  },
  {
    title: "Sword Art Online",
    imageURL: "https://myanimelist.cdn-dena.com/images/anime/11/39717.jpg",
    year: 2017,
    units: 10,
  },
  {
    title: "Log Horizon",
    imageURL: "https://myanimelist.cdn-dena.com/images/anime/5/84004.jpg",
    year: 2017,
    units: 10,
  },
  {
    title: "Steins Gate 0",
    imageURL: "https://myanimelist.cdn-dena.com/images/anime/4/77633.jpg",
    year: 2017,
    units: 10,
  },
  {
    title: "One Punch Man",
    imageURL: "https://myanimelist.cdn-dena.com/images/anime/12/76049.jpg",
    year: 2017,
    units: 10,
  },
];
